# Generated by Django 2.2.13 on 2021-07-14 04:03

import os
import json

from django.db import migrations, models
from gatherer.models import (
    DigestRecordDuplicate,
    DigestIssue,
)
import logging

def fill_issues_in_duplicates(apps, schema_editor):
    for duplicate in DigestRecordDuplicate.objects.all():
        try:
            issue = DigestIssue.objects.get(number=duplicate.digest_number)
        except Exception as e:
            logging.error(f'Failed to find digest issue with number {duplicate.digest_number}')
            continue
        duplicate.digest_issue = issue
        duplicate.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0051_add_digestrecordduplicate_digest_issue'),
    ]

    operations = [
        migrations.RunPython(fill_issues_in_duplicates, migrations.RunPython.noop),
    ]
